version: '3.8'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root@user
      - POSTGRES_DB=StoreUser
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    restart: unless-stopped

volumes:
  postgres: